#!/usr/bin/env bash
# script that installs Nginx web server and sets a listening port to 80

sudo apt-get -y update
sudo apt-get -y install nginx
echo 'Hello World!' | sudo tee /var/www/html/index.html
service nginx start
