#!/usr/bin/env bash
# script that generates a MySQL dump and creates a compressed archive out of it

mysqldump -u root --password=$1 --all-databases > backup.sql

DATE_FORMAT=$(date +"%d-%m-%Y")

tar -czvf "$DATE_FORMAT.tar.gz" backup.sql
