#!/bin/bash
apt-get update
apt-get install -y nginx
echo "server { listen 80; listen [::]:80; location / { return 200 'Hello, World!'; } }" > /etc/nginx/sites-available/default
service nginx start
curl -s http://100.25.144.134:80
